environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      FLANN_VERSION: "1.9.1"
      NUMPY_VERSION: "1.11"
      MINICONDA: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.6"
      FLANN_VERSION: "1.9.1"
      NUMPY_VERSION: "1.14"
      MINICONDA: "C:\\Miniconda36-x64"

platform:
  - x64

install:
  - cmd: rmdir C:\cygwin /s /q

  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: conda config --add channels conda-forge

  - cmd: conda create -n env --yes --quiet python=%PYTHON_VERSION% pytest setuptools wheel cython numpy=%NUMPY_VERSION% flann=%FLANN_VERSION% pyflann m2w64-pkg-config
  - cmd: conda activate env

  - cmd: python setup.py flann_info install

build: off

test_script:
  - mkdir empty_folder
  - cd empty_folder
  - python -m pytest --pyargs cyflann
  - cd ..
